### ISSUE TITLE
Iternant Ink Causes Problems on Servers

### ISSUE THREAD

**Issue by milkev** [Ladysnake/Nomad-Books#15]
Applying iternant ink causes me to be kicked from my server. Said there was a packet error.
I had to change my nbt data to be able to rejoin the game.

**Comment by dclay1983** [comment]
Still happening

**Comment by doctor4t** [comment]
Still waiting for an actual crash report / log

**Comment by doctor4t** [comment]
@dclay1983 
![image](https://user-images.githubusercontent.com/25477005/87598968-a7a23700-c6f3-11ea-82b5-66961c4bc489.png)

**Comment by dclay1983** [comment]
This is from the output on the console. Sadly no crash log was created. 
```
15.07 14:22:04 [Server] Server thread/WARN Failed to handle packet for /{ipaddress}
15.07 14:22:04 [Server] INFO net.minecraft.class_148: Ticking player
15.07 14:22:04 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:485) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:206) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:233) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:170) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:884) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:306) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
15.07 14:22:04 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1959.method_8693()Lnet/minecraft/class_2561;
15.07 14:22:04 [Server] INFO at net.minecraft.class_3222.handler$zzn000$enterBiome(class_3222.java:1622) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:477) ~[intermediary-server.jar:?]
15.07 14:22:04 [Server] INFO ... 9 more
```

**Comment by milkev** [comment]
ah im sorry, i didnt realize open = give me log
ill get another one later if dclay's isnt enough

**Comment by doctor4t** [comment]
@milkev Oh no not at all, it's not that. Open means unresolved, I was therefore pointing that out to them because of their comment. But when you report an issue, it's always best if you can provide logs and reports from the beginning, as that helps solving the issue faster.
I'd still prefer if you gave me logs too, at least to make sure it's the same issue.
